In [1]:
import numpy as np


In [2]:
l1=[10,20,30]
arr1=np.array(l1)
print(arr1)

[10 20 30]


In [4]:
print(arr1[0])
print(arr1[0:2])

10
[10 20]


In [5]:
l2=[[1,2,3],[4,5,6]]
arr2=np.array(l2)
print(arr2)

[[1 2 3]
 [4 5 6]]


In [10]:
print(arr2[: 1])
print(arr2[0,1])

[[1 2 3]]
2


In [12]:
arr3=np.array([10,1.4,3.2,20])
print(arr3)
print(arr3.ndim)
print(arr3.shape)
print(arr3.size)
print(arr3.dtype)
print(arr3.itemsize)

[10.   1.4  3.2 20. ]
1
(4,)
4
float64
8


In [13]:
az1=np.zeros(5)
print(az1)

[0. 0. 0. 0. 0.]


In [14]:
az2=np.zeros(5,dtype=np.uint8)
print(az2)

[0 0 0 0 0]


In [18]:
az3=np.ones(5)
print(az3)

[1. 1. 1. 1. 1.]


In [19]:
az4=np.ones(5,dtype=np.uint8)
print(az4)

[1 1 1 1 1]


In [20]:
aa1=np.arange(2,11,3,dtype=np.uint8)
print(aa1)

[2 5 8]


In [21]:
bb=np.linspace(1,100,25)
print(bb)

[  1.      5.125   9.25   13.375  17.5    21.625  25.75   29.875  34.
  38.125  42.25   46.375  50.5    54.625  58.75   62.875  67.     71.125
  75.25   79.375  83.5    87.625  91.75   95.875 100.   ]


In [24]:
arr6=np.array([1,2,3,4])
arr7=arr6.reshape([2,2])
print(arr7)

[[1 2]
 [3 4]]
