<h1 style = "color:Brown">Objectives</h1>

### 1. Loading data.
### 2. Checking for missing values.
### 3. Splitting the data in to train set and test set.




<h2 style = "color:green">Loading Data</h2>

In [3]:
# Load the data from external flat file - use pandas.read_csv() or pandas.read_excel()
import pandas as pd
df1=pd.read_csv("churn-modelling.csv")
print(df1.shape)
print(df1.columns)
print(df1.head(3))

(10000, 7)
Index(['CreditScore', 'Age', 'Tenure', 'Balance', 'HasCrCard', 'Salary',
       'Exited'],
      dtype='object')
   CreditScore  Age  Tenure    Balance  HasCrCard     Salary  Exited
0          619   42       2       0.00          1  101348.88       1
1          608   41       1   83807.86          0  112542.58       0
2          502   42       8  159660.80          1  113931.57       1


In [4]:
# Load the data from sklearn.datasets - load_iris(), load_diabetes(), load_digits(), load_linnerud(), load_wine(), load_breast_cancer()
from sklearn.datasets import load_iris
dataset=load_iris()
print(type(dataset))
X=dataset.data
print(X.shape)
print(type(X))
print(X[0:5])
print(dataset.feature_names)
Y=dataset.target
print(type(Y))
print(Y[145:150])
print(dataset.target_names)
# Parameter return_X_y=True returns the data set as separate input and output numpy arrays as ndobjects

<class 'sklearn.utils._bunch.Bunch'>
(150, 4)
<class 'numpy.ndarray'>
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
<class 'numpy.ndarray'>
[2 2 2 2 2]
['setosa' 'versicolor' 'virginica']


In [7]:
#Loading the dataset as separate input and output numpy arrays as ndobjects
X,y=load_iris(return_X_y=True)
print(type(X))
print(X[0:4])
print(type(y))
print(Y[0:5])

<class 'numpy.ndarray'>
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]]
<class 'numpy.ndarray'>
[0 0 0 0 0]


In [9]:
# Parameter as_frame=True returns the data as a dataframe.
X,y=load_iris(return_X_y=True,as_frame=True)
print(type(X))
print(X[0:6])

<class 'pandas.core.frame.DataFrame'>
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
5                5.4               3.9                1.7               0.4


<h2 style = "color:green">pandas.isna(object)</h2>

### Detects missing values.
### Returns a boolen object of same size.
### None and np.NaN are mapped True values. Everything else gets mapped to False values.

In [10]:
df1.isna().sum()

CreditScore    0
Age            0
Tenure         0
Balance        0
HasCrCard      0
Salary         0
Exited         0
dtype: int64

In [11]:
x=df1.drop('Exited',axis=1)

In [12]:
y=df1['Exited']

In [14]:
# Split the data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.7)
print(x_train)
print(y_train)
print(x_test)
print(y_test)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

      CreditScore  Age  Tenure    Balance  HasCrCard     Salary
1148          613   34       3       0.00          1   41724.72
9689          698   57       9  111359.55          1  105715.01
7324          607   39      10       0.00          1  132741.13
2647          461   51       9  119889.84          0   56767.67
668           695   46       3  122549.64          1   56297.85
...           ...  ...     ...        ...        ...        ...
4320          701   36       7   95448.32          1  189085.07
9802          756   40       1   94773.11          1  114279.63
9492          732   48       4  102962.62          1  120852.85
3671          646   52       6  111739.40          0   68367.18
2567          553   42       1       0.00          0   23822.04

[3000 rows x 6 columns]
1148    0
9689    0
7324    1
2647    1
668     0
       ..
4320    0
9802    0
9492    1
3671    0
2567    0
Name: Exited, Length: 3000, dtype: int64
      CreditScore  Age  Tenure    Balance  HasCrCard    

#### We can use random_state keyword argument to get same set of training and testing samples.

In [17]:
x_train, x_test, y_train, y_test=train_test_split(x,y, test_size=3000,random_state=37)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(7000, 6)
(3000, 6)
(7000,)
(3000,)
